"""Add unique constraint on username per parent

Revision ID: bcfaa9596995
Revises: 
Create Date: 2026-05-09 20:20:25.853993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcfaa9596995'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_username_per_parent', ['username', 'parent_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('unique_username_per_parent', type_='unique')

    # ### end Alembic commands ###
